apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: terraform-provider-rhcs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: terraform-provider-rhcs
    app.kubernetes.io/part-of: terraform-provider-rhcs
  name: terraform-provider-rhcs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: terraform-provider-rhcs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: terraform-provider-rhcs
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-terraform-tenant/terraform-provider-rhcs/terraform-provider-rhcs@sha256:ec983218a0d94ba4ae89c8a17e2209b9935ed1446707541cb254110768ca2806
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
